title: Amazón códé  || Setup Amazón prime Account || Activate códé  for Amazón prime
description: Create your prime account and Amazón.com/códé  and enter 6-character Amazón activation códé  and add channels to your list.
